// config.js
// Configuration for the mobile app

/* ──────────────────────────────────────────────
 *  SERVER CONFIGURATION
 * ────────────────────────────────────────────── */

// HTTPS via Cloudflare - use standard HTTPS port
export const SERVER_HOST = 'text.fasbit.com';
export const SERVER_PORT = '443';
export const USE_HTTPS = true;

/* ──────────────────────────────────────────────
 *  CLIENT AUTHENTICATION
 * ────────────────────────────────────────────── */

// Client ID - must match CLIENTS configuration on server
export const CLIENT_ID = 'client-1';

// Ed25519 private key used to sign requests
// Generated by genKeys.js - keep this private!
export const SECRET_KEY_BASE64 =
  'smfgQAnsJMwB91GgJDh1jaGupVeuisYREtz8HAHIvv/r4kG87MVWquYRYo+gx/BxM08b1eDhVEttXaqJBPmDKw==';

/* ──────────────────────────────────────────────
 *  DEFAULT SETTINGS
 * ────────────────────────────────────────────── */

export const DEFAULT_SETTINGS = {
  serverHost: SERVER_HOST,
  serverPort: SERVER_PORT,
  useHttps: USE_HTTPS,
  defaultFormat: 'jpg',      // 'jpg' or 'png'
  maxMegapixels: 4,          // Resize images to max 4 megapixels
  networkPreference: 'any',  // 'any' | 'wifi' | 'cellular'
};